-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.book
(
    book_id serial NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    edition character varying(50) COLLATE pg_catalog."default",
    author character varying(100) COLLATE pg_catalog."default" NOT NULL,
    total_copies integer NOT NULL,
    available_copies integer NOT NULL,
    cost numeric(10, 2),
    source character varying(100) COLLATE pg_catalog."default",
    created_at timestamp without time zone,
    CONSTRAINT book_pkey PRIMARY KEY (book_id)
);

CREATE TABLE IF NOT EXISTS public.transaction_record
(
    transaction_id serial NOT NULL,
    user_id integer NOT NULL,
    book_id integer NOT NULL,
    borrow_date timestamp without time zone,
    return_date timestamp without time zone,
    is_returned boolean,
    overdue_days integer,
    fine_imposed numeric(10, 2),
    created_at timestamp without time zone,
    CONSTRAINT transaction_record_pkey PRIMARY KEY (transaction_id)
);

CREATE TABLE IF NOT EXISTS public."user"
(
    user_id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    contact_number character varying(15) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    user_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    fine_due numeric(10, 2),
    created_at timestamp without time zone,
    CONSTRAINT user_pkey PRIMARY KEY (user_id),
    CONSTRAINT user_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public.transaction_record
    ADD CONSTRAINT transaction_record_book_id_fkey FOREIGN KEY (book_id)
    REFERENCES public.book (book_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.transaction_record
    ADD CONSTRAINT transaction_record_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public."user" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;